version: '3.9'

services:
  postgres-dev:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  auth-service:
    build: ./auth-service
    ports:
      - '8081:8080'
    depends_on:
      - postgres-dev
  tenant-service:
    build: ./tenant-service
    ports:
      - '8082:8080'
    depends_on:
      - postgres-dev
  assessment-service:
    build: ./assessment-service
    ports:
      - '8083:8080'
    depends_on:
      - postgres-dev
  adaptive-education-service:
    build: ./adaptive-education-service
    ports:
      - '8084:8080'
    depends_on:
      - postgres-dev
  notification-service:
    build: ./notification-service
    ports:
      - '8085:8080'
    depends_on:
      - postgres-dev
  gateway-service:
    build: ./gateway-service
    ports:
      - '8086:8080'
    depends_on:
      - postgres-dev
  commons-service:
    build: ./commons-service
    ports:
      - '8087:8080'
    depends_on:
      - postgres-dev
  report-service:
    build: ./report-service
    ports:
      - '8088:8080'
    depends_on:
      - postgres-dev
  monitoring-service:
    build: ./monitoring-service
    ports:
      - '8089:8080'
    depends_on:
      - postgres-dev

volumes:
  postgres-data:
