sonar.projectKey=jamartinezv2023_ilp_backend
sonar.organization=jamartinezv2023
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.java.binaries=**/build/classes
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=**/build/**,**/.gradle/**,**/generated/**
