sonar.projectKey=TU_PROJECT_KEY
sonar.organization=TU_ORGANIZATION

sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.

sonar.java.binaries=**/build/classes

sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=**/build/**,**/.gradle/**,**/generated/**

sonar.qualitygate.wait=true
