CREATE TABLE IF NOT EXISTS user_mfa (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  mfa_type VARCHAR(16) NOT NULL DEFAULT 'TOTP', -- futuro: EMAIL/SMS/TOTP/NONE
  secret VARCHAR(128),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_updated_at_user_mfa()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_mfa_updated_at ON user_mfa;
CREATE TRIGGER trg_user_mfa_updated_at
BEFORE UPDATE ON user_mfa
FOR EACH ROW EXECUTE FUNCTION set_updated_at_user_mfa();