server:
  port: 8085

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ilp_db # Asegúrate de que esta DB exista
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:change-me}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Esta línea ayuda a evitar conflictos de nombres de columnas
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/