--
-- PostgreSQL database dump
--

\restrict bTFbdteLxXfNV6oqYacRQb5NxOY8mvlYVmZUf6niG7sTFxywX6jeuN9mUeHL7AW

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: adaptation_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptation_rules (
    id bigint NOT NULL,
    adjustment_content character varying(255),
    style_key character varying(255),
    style_value character varying(255)
);


--
-- Name: adaptation_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.adaptation_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adaptation_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adaptive_learning_plan_family_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptive_learning_plan_family_actions (
    plan_id character varying(255) NOT NULL,
    family_action character varying(1000) NOT NULL
);


--
-- Name: adaptive_learning_plan_inclusion_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptive_learning_plan_inclusion_actions (
    plan_id character varying(255) NOT NULL,
    inclusion_action character varying(1000) NOT NULL
);


--
-- Name: adaptive_learning_plan_pathway; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptive_learning_plan_pathway (
    plan_id character varying(255) NOT NULL,
    pathway_step character varying(1000) NOT NULL
);


--
-- Name: adaptive_learning_plan_resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptive_learning_plan_resources (
    plan_id character varying(255) NOT NULL,
    resource character varying(1000) NOT NULL
);


--
-- Name: adaptive_learning_plan_teacher_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptive_learning_plan_teacher_actions (
    plan_id character varying(255) NOT NULL,
    teacher_action character varying(1000) NOT NULL
);


--
-- Name: adaptive_learning_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adaptive_learning_plans (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    recommended_methodology character varying(255) NOT NULL,
    risk_level character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL
);


--
-- Name: assessment_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_answers (
    id character varying(255) NOT NULL,
    dimension character varying(255) NOT NULL,
    option_id character varying(255) NOT NULL,
    question_id character varying(255) NOT NULL,
    score integer NOT NULL,
    answer_value character varying(255) NOT NULL,
    assessment_response_id character varying(255) NOT NULL
);


--
-- Name: assessment_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_definitions (
    id character varying(255) NOT NULL,
    active boolean NOT NULL,
    assessment_type character varying(255) NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(2000) NOT NULL,
    estimated_minutes integer NOT NULL,
    instructions character varying(4000) NOT NULL,
    name character varying(255) NOT NULL,
    version character varying(255) NOT NULL
);


--
-- Name: assessment_interpretations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_interpretations (
    id character varying(255) NOT NULL,
    result_id character varying(255) NOT NULL,
    administration_id character varying(255) NOT NULL,
    interpretation_code character varying(255) NOT NULL,
    interpretation_text character varying(255),
    interpretation_version character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: assessment_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_options (
    id character varying(255) NOT NULL,
    display_order integer NOT NULL,
    label character varying(255) NOT NULL,
    option_value character varying(255) NOT NULL,
    weight integer NOT NULL,
    question_id character varying(255) NOT NULL
);


--
-- Name: assessment_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_questions (
    id character varying(255) NOT NULL,
    dimension character varying(255) NOT NULL,
    display_order integer NOT NULL,
    help_text character varying(2000) NOT NULL,
    question_number integer NOT NULL,
    question_type character varying(255) NOT NULL,
    required boolean NOT NULL,
    text character varying(2000) NOT NULL,
    assessment_definition_id character varying(255) NOT NULL
);


--
-- Name: assessment_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_responses (
    id character varying(255) NOT NULL,
    assessment_code character varying(255) NOT NULL,
    assessment_version character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL,
    submitted_at timestamp(6) with time zone NOT NULL
);


--
-- Name: assessment_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_results (
    id character varying(255) NOT NULL,
    administration_id character varying(255) NOT NULL,
    participant_id character varying(255) NOT NULL,
    assessment_code character varying(255) NOT NULL,
    assessment_version character varying(255) NOT NULL,
    primary_profile character varying(255),
    scoring_algorithm_version character varying(255) NOT NULL,
    interpretation_version character varying(255),
    calculated_at timestamp with time zone NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    feature_cutoff_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: assessment_score_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_score_items (
    id character varying(255) NOT NULL,
    result_id character varying(255) NOT NULL,
    administration_id character varying(255) NOT NULL,
    dimension_code character varying(255) NOT NULL,
    numeric_value double precision NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: assessment_submission_context; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_submission_context (
    id character varying(255) NOT NULL,
    administration_id character varying(255) NOT NULL,
    institution_id character varying(255),
    campus_id character varying(255),
    program_id character varying(255),
    course_id character varying(255),
    cohort_id character varying(255),
    teacher_id character varying(255),
    grade character varying(100),
    academic_year character varying(20),
    academic_period character varying(100),
    fieldwork_phase character varying(100),
    intervention_id character varying(255),
    intervention_group character varying(100),
    source character varying(100),
    delivery_mode character varying(100),
    language character varying(20),
    device_type character varying(100),
    browser character varying(255),
    operating_system character varying(255),
    timezone character varying(100),
    application_version character varying(100),
    consent_id character varying(255),
    consent_version character varying(100),
    ethics_protocol character varying(255),
    feature_set_version character varying(100),
    preprocessing_version character varying(100),
    normalization_version character varying(100),
    started_at timestamp with time zone,
    duration_seconds bigint,
    feature_cutoff_at timestamp with time zone NOT NULL,
    context_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_assessment_submission_duration CHECK (((duration_seconds IS NULL) OR (duration_seconds >= 0)))
);


--
-- Name: educational_interventions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.educational_interventions (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(1500) NOT NULL,
    intervention_type character varying(255) NOT NULL,
    responsible_role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: felder_silverman_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.felder_silverman_answers (
    assessment_id character varying(255) NOT NULL,
    answer_value character varying(255) NOT NULL
);


--
-- Name: felder_silverman_assessment_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.felder_silverman_assessment_results (
    id character varying(255) NOT NULL,
    active_reflective_score integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    dominant_profile character varying(255) NOT NULL,
    instrument_version character varying(255) NOT NULL,
    sensing_intuitive_score integer NOT NULL,
    sequential_global_score integer NOT NULL,
    student_id character varying(255) NOT NULL,
    visual_verbal_score integer NOT NULL
);


--
-- Name: felder_silverman_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.felder_silverman_preferences (
    assessment_id character varying(255) NOT NULL,
    preference character varying(255) NOT NULL
);


--
-- Name: fieldwork_consent_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fieldwork_consent_records (
    consent_id uuid NOT NULL,
    approved_at timestamp(6) without time zone,
    consent_type character varying(255),
    created_at timestamp(6) without time zone,
    participant_code character varying(255),
    status character varying(255),
    withdrawn_at timestamp(6) without time zone
);


--
-- Name: fieldwork_research_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fieldwork_research_participants (
    participant_uuid uuid NOT NULL,
    cohort_code character varying(255),
    consent_status character varying(255),
    created_at timestamp(6) without time zone,
    participant_code character varying(255)
);


--
-- Name: instrument_question_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instrument_question_options (
    question_id character varying(255) NOT NULL,
    option_text character varying(1000) NOT NULL
);


--
-- Name: instrument_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instrument_questions (
    id character varying(255) NOT NULL,
    dimension character varying(255) NOT NULL,
    instrument character varying(255) NOT NULL,
    instrument_version character varying(255) NOT NULL,
    question_order integer NOT NULL,
    text character varying(1500) NOT NULL
);


--
-- Name: kolb_assessment_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kolb_assessment_answers (
    assessment_id character varying(255) NOT NULL,
    answer_value integer NOT NULL
);


--
-- Name: kolb_assessment_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kolb_assessment_results (
    id character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    instrument_version character varying(255) NOT NULL,
    learning_style character varying(255) NOT NULL,
    scoreac integer NOT NULL,
    scoreae integer NOT NULL,
    scorece integer NOT NULL,
    scorero integer NOT NULL,
    student_id character varying(255) NOT NULL
);


--
-- Name: kuder_assessment_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kuder_assessment_answers (
    assessment_id character varying(255) NOT NULL,
    answer_value character varying(255) NOT NULL
);


--
-- Name: kuder_assessment_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kuder_assessment_results (
    id character varying(255) NOT NULL,
    administrative_score integer NOT NULL,
    artistic_score integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    dominant_vocational_area character varying(255) NOT NULL,
    instrument_version character varying(255) NOT NULL,
    mechanical_score integer NOT NULL,
    scientific_score integer NOT NULL,
    social_score integer NOT NULL,
    student_id character varying(255) NOT NULL
);


--
-- Name: kuder_top_vocational_areas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kuder_top_vocational_areas (
    assessment_id character varying(255) NOT NULL,
    vocational_area character varying(255) NOT NULL
);


--
-- Name: learning_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_recommendations (
    id bigint NOT NULL,
    content character varying(255),
    student_id bigint
);


--
-- Name: learning_recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ml_experiments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ml_experiments (
    id character varying(255) NOT NULL,
    accuracy double precision NOT NULL,
    algorithm character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    f1score double precision NOT NULL,
    feature_importance_json character varying(3000) NOT NULL,
    precision_score double precision NOT NULL,
    recall_score double precision NOT NULL,
    target character varying(255) NOT NULL,
    test_rows integer NOT NULL,
    total_rows integer NOT NULL,
    train_rows integer NOT NULL,
    validation_rows integer NOT NULL
);


--
-- Name: scientific_feature_generation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scientific_feature_generation_runs (
    id character varying(100) NOT NULL,
    participant_id character varying(100) NOT NULL,
    feature_set_version character varying(100) NOT NULL,
    generator_version character varying(100) NOT NULL,
    feature_cutoff_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    status character varying(30) NOT NULL,
    input_observation_count integer NOT NULL,
    error_message text,
    feature_vector_id character varying(100),
    CONSTRAINT chk_scientific_feature_run_completion CHECK (((((status)::text = 'STARTED'::text) AND (completed_at IS NULL) AND (error_message IS NULL)) OR (((status)::text = 'COMPLETED'::text) AND (completed_at IS NOT NULL) AND (error_message IS NULL) AND (feature_vector_id IS NOT NULL)) OR (((status)::text = 'FAILED'::text) AND (completed_at IS NOT NULL) AND (error_message IS NOT NULL)))),
    CONSTRAINT chk_scientific_feature_run_input_count CHECK ((input_observation_count >= 0)),
    CONSTRAINT chk_scientific_feature_run_status CHECK (((status)::text = ANY ((ARRAY['STARTED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: scientific_feature_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scientific_feature_items (
    id character varying(120) NOT NULL,
    feature_vector_id character varying(100) NOT NULL,
    feature_code character varying(100) NOT NULL,
    data_type character varying(30) NOT NULL,
    numeric_value double precision,
    text_value text,
    boolean_value boolean,
    source_assessment_code character varying(100),
    source_administration_id character varying(100),
    CONSTRAINT chk_scientific_feature_item_data_type CHECK (((data_type)::text = ANY ((ARRAY['NUMERIC'::character varying, 'TEXT'::character varying, 'BOOLEAN'::character varying])::text[]))),
    CONSTRAINT chk_scientific_feature_item_single_value CHECK (((((data_type)::text = 'NUMERIC'::text) AND (numeric_value IS NOT NULL) AND (text_value IS NULL) AND (boolean_value IS NULL)) OR (((data_type)::text = 'TEXT'::text) AND (numeric_value IS NULL) AND (text_value IS NOT NULL) AND (boolean_value IS NULL)) OR (((data_type)::text = 'BOOLEAN'::text) AND (numeric_value IS NULL) AND (text_value IS NULL) AND (boolean_value IS NOT NULL))))
);


--
-- Name: scientific_feature_vectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scientific_feature_vectors (
    id character varying(100) NOT NULL,
    participant_id character varying(100) NOT NULL,
    feature_set_version character varying(100) NOT NULL,
    generator_version character varying(100) NOT NULL,
    feature_cutoff_at timestamp with time zone NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    source_observation_count integer NOT NULL,
    status character varying(30) NOT NULL,
    checksum character varying(128) NOT NULL,
    CONSTRAINT chk_scientific_feature_vector_observation_count CHECK ((source_observation_count >= 0)),
    CONSTRAINT chk_scientific_feature_vector_status CHECK (((status)::text = ANY ((ARRAY['GENERATING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: student_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_features (
    id character varying(255) NOT NULL,
    feature_date timestamp(6) with time zone NOT NULL,
    kolb_ac integer NOT NULL,
    kolb_ae integer NOT NULL,
    kolb_ce integer NOT NULL,
    kolb_ro integer NOT NULL,
    kolb_style character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL
);


--
-- Name: student_inclusive_strategies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_inclusive_strategies (
    student_id character varying(255) NOT NULL,
    strategy character varying(1000) NOT NULL
);


--
-- Name: student_learning_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_learning_preferences (
    student_id character varying(255) NOT NULL,
    preference character varying(500) NOT NULL
);


--
-- Name: student_pedagogical_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_pedagogical_recommendations (
    student_id character varying(255) NOT NULL,
    recommendation character varying(1000) NOT NULL
);


--
-- Name: student_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_profiles (
    id character varying(255) NOT NULL,
    age integer NOT NULL,
    full_name character varying(255) NOT NULL,
    grade character varying(255) NOT NULL,
    learning_profile character varying(255) NOT NULL,
    support_level character varying(255) NOT NULL,
    vocational_interest character varying(255) NOT NULL
);


--
-- Name: adaptation_rules adaptation_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptation_rules
    ADD CONSTRAINT adaptation_rules_pkey PRIMARY KEY (id);


--
-- Name: adaptive_learning_plans adaptive_learning_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptive_learning_plans
    ADD CONSTRAINT adaptive_learning_plans_pkey PRIMARY KEY (id);


--
-- Name: assessment_answers assessment_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_answers
    ADD CONSTRAINT assessment_answers_pkey PRIMARY KEY (id);


--
-- Name: assessment_definitions assessment_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_definitions
    ADD CONSTRAINT assessment_definitions_pkey PRIMARY KEY (id);


--
-- Name: assessment_interpretations assessment_interpretations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_interpretations
    ADD CONSTRAINT assessment_interpretations_pkey PRIMARY KEY (id);


--
-- Name: assessment_options assessment_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_options
    ADD CONSTRAINT assessment_options_pkey PRIMARY KEY (id);


--
-- Name: assessment_questions assessment_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_questions
    ADD CONSTRAINT assessment_questions_pkey PRIMARY KEY (id);


--
-- Name: assessment_responses assessment_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_responses
    ADD CONSTRAINT assessment_responses_pkey PRIMARY KEY (id);


--
-- Name: assessment_results assessment_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT assessment_results_pkey PRIMARY KEY (id);


--
-- Name: assessment_score_items assessment_score_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_score_items
    ADD CONSTRAINT assessment_score_items_pkey PRIMARY KEY (id);


--
-- Name: assessment_submission_context assessment_submission_context_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_submission_context
    ADD CONSTRAINT assessment_submission_context_pkey PRIMARY KEY (id);


--
-- Name: educational_interventions educational_interventions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.educational_interventions
    ADD CONSTRAINT educational_interventions_pkey PRIMARY KEY (id);


--
-- Name: felder_silverman_assessment_results felder_silverman_assessment_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.felder_silverman_assessment_results
    ADD CONSTRAINT felder_silverman_assessment_results_pkey PRIMARY KEY (id);


--
-- Name: fieldwork_consent_records fieldwork_consent_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fieldwork_consent_records
    ADD CONSTRAINT fieldwork_consent_records_pkey PRIMARY KEY (consent_id);


--
-- Name: fieldwork_research_participants fieldwork_research_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fieldwork_research_participants
    ADD CONSTRAINT fieldwork_research_participants_pkey PRIMARY KEY (participant_uuid);


--
-- Name: instrument_questions instrument_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instrument_questions
    ADD CONSTRAINT instrument_questions_pkey PRIMARY KEY (id);


--
-- Name: kolb_assessment_results kolb_assessment_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kolb_assessment_results
    ADD CONSTRAINT kolb_assessment_results_pkey PRIMARY KEY (id);


--
-- Name: kuder_assessment_results kuder_assessment_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kuder_assessment_results
    ADD CONSTRAINT kuder_assessment_results_pkey PRIMARY KEY (id);


--
-- Name: learning_recommendations learning_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_recommendations
    ADD CONSTRAINT learning_recommendations_pkey PRIMARY KEY (id);


--
-- Name: ml_experiments ml_experiments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ml_experiments
    ADD CONSTRAINT ml_experiments_pkey PRIMARY KEY (id);


--
-- Name: scientific_feature_generation_runs scientific_feature_generation_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_generation_runs
    ADD CONSTRAINT scientific_feature_generation_runs_pkey PRIMARY KEY (id);


--
-- Name: scientific_feature_items scientific_feature_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_items
    ADD CONSTRAINT scientific_feature_items_pkey PRIMARY KEY (id);


--
-- Name: scientific_feature_vectors scientific_feature_vectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_vectors
    ADD CONSTRAINT scientific_feature_vectors_pkey PRIMARY KEY (id);


--
-- Name: student_features student_features_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_features
    ADD CONSTRAINT student_features_pkey PRIMARY KEY (id);


--
-- Name: student_profiles student_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_pkey PRIMARY KEY (id);


--
-- Name: assessment_definitions ukhjjjh1i5rph3mn339de87g0c8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_definitions
    ADD CONSTRAINT ukhjjjh1i5rph3mn339de87g0c8 UNIQUE (code);


--
-- Name: assessment_interpretations uq_assessment_interpretation_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_interpretations
    ADD CONSTRAINT uq_assessment_interpretation_code UNIQUE (result_id, interpretation_code);


--
-- Name: assessment_results uq_assessment_results_administration; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT uq_assessment_results_administration UNIQUE (administration_id);


--
-- Name: assessment_score_items uq_assessment_score_dimension; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_score_items
    ADD CONSTRAINT uq_assessment_score_dimension UNIQUE (result_id, dimension_code);


--
-- Name: assessment_submission_context uq_assessment_submission_context_administration; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_submission_context
    ADD CONSTRAINT uq_assessment_submission_context_administration UNIQUE (administration_id);


--
-- Name: scientific_feature_items uq_scientific_feature_item_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_items
    ADD CONSTRAINT uq_scientific_feature_item_code UNIQUE (feature_vector_id, feature_code);


--
-- Name: scientific_feature_vectors uq_scientific_feature_vector_identity; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_vectors
    ADD CONSTRAINT uq_scientific_feature_vector_identity UNIQUE (participant_id, feature_set_version, feature_cutoff_at);


--
-- Name: idx_assessment_context_cohort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_context_cohort ON public.assessment_submission_context USING btree (cohort_id);


--
-- Name: idx_assessment_context_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_context_course ON public.assessment_submission_context USING btree (course_id);


--
-- Name: idx_assessment_context_feature_cutoff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_context_feature_cutoff ON public.assessment_submission_context USING btree (feature_cutoff_at);


--
-- Name: idx_assessment_context_fieldwork; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_context_fieldwork ON public.assessment_submission_context USING btree (fieldwork_phase);


--
-- Name: idx_assessment_context_institution_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_context_institution_period ON public.assessment_submission_context USING btree (institution_id, academic_year, academic_period);


--
-- Name: idx_assessment_interpretation_administration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_interpretation_administration ON public.assessment_interpretations USING btree (administration_id);


--
-- Name: idx_assessment_results_feature_cutoff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_results_feature_cutoff ON public.assessment_results USING btree (feature_cutoff_at);


--
-- Name: idx_assessment_results_instrument; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_results_instrument ON public.assessment_results USING btree (assessment_code, assessment_version);


--
-- Name: idx_assessment_results_participant_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_results_participant_time ON public.assessment_results USING btree (participant_id, calculated_at);


--
-- Name: idx_assessment_score_administration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_score_administration ON public.assessment_score_items USING btree (administration_id);


--
-- Name: idx_assessment_score_dimension; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assessment_score_dimension ON public.assessment_score_items USING btree (dimension_code);


--
-- Name: idx_scientific_feature_items_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_items_code ON public.scientific_feature_items USING btree (feature_code);


--
-- Name: idx_scientific_feature_items_source_administration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_items_source_administration ON public.scientific_feature_items USING btree (source_administration_id);


--
-- Name: idx_scientific_feature_items_vector; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_items_vector ON public.scientific_feature_items USING btree (feature_vector_id);


--
-- Name: idx_scientific_feature_runs_cutoff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_runs_cutoff ON public.scientific_feature_generation_runs USING btree (feature_cutoff_at);


--
-- Name: idx_scientific_feature_runs_participant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_runs_participant ON public.scientific_feature_generation_runs USING btree (participant_id);


--
-- Name: idx_scientific_feature_runs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_runs_status ON public.scientific_feature_generation_runs USING btree (status);


--
-- Name: idx_scientific_feature_vectors_cutoff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_vectors_cutoff ON public.scientific_feature_vectors USING btree (feature_cutoff_at);


--
-- Name: idx_scientific_feature_vectors_latest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_vectors_latest ON public.scientific_feature_vectors USING btree (participant_id, feature_set_version, feature_cutoff_at DESC);


--
-- Name: idx_scientific_feature_vectors_participant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scientific_feature_vectors_participant ON public.scientific_feature_vectors USING btree (participant_id);


--
-- Name: student_inclusive_strategies fk10tk1u1n96gssbw8d2iffib0m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_inclusive_strategies
    ADD CONSTRAINT fk10tk1u1n96gssbw8d2iffib0m FOREIGN KEY (student_id) REFERENCES public.student_profiles(id);


--
-- Name: adaptive_learning_plan_inclusion_actions fk2cdxyxpscf9wecixhy3e9udlt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptive_learning_plan_inclusion_actions
    ADD CONSTRAINT fk2cdxyxpscf9wecixhy3e9udlt FOREIGN KEY (plan_id) REFERENCES public.adaptive_learning_plans(id);


--
-- Name: student_pedagogical_recommendations fk2qsigxm97yo1awp1xxv00c865; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_pedagogical_recommendations
    ADD CONSTRAINT fk2qsigxm97yo1awp1xxv00c865 FOREIGN KEY (student_id) REFERENCES public.student_profiles(id);


--
-- Name: adaptive_learning_plan_resources fk6k3petwayyuq5chxs7qnxc4t5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptive_learning_plan_resources
    ADD CONSTRAINT fk6k3petwayyuq5chxs7qnxc4t5 FOREIGN KEY (plan_id) REFERENCES public.adaptive_learning_plans(id);


--
-- Name: felder_silverman_preferences fk79v3ci5ap130yc3cnv94vfotn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.felder_silverman_preferences
    ADD CONSTRAINT fk79v3ci5ap130yc3cnv94vfotn FOREIGN KEY (assessment_id) REFERENCES public.felder_silverman_assessment_results(id);


--
-- Name: adaptive_learning_plan_teacher_actions fk8f1ws8n4diubyadcr4sruk31x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptive_learning_plan_teacher_actions
    ADD CONSTRAINT fk8f1ws8n4diubyadcr4sruk31x FOREIGN KEY (plan_id) REFERENCES public.adaptive_learning_plans(id);


--
-- Name: kolb_assessment_answers fk9j4u61li59s0fvbllvdrdfw78; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kolb_assessment_answers
    ADD CONSTRAINT fk9j4u61li59s0fvbllvdrdfw78 FOREIGN KEY (assessment_id) REFERENCES public.kolb_assessment_results(id);


--
-- Name: student_learning_preferences fk9ti3nss3r61qwc2cxx3s5xlwc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_learning_preferences
    ADD CONSTRAINT fk9ti3nss3r61qwc2cxx3s5xlwc FOREIGN KEY (student_id) REFERENCES public.student_profiles(id);


--
-- Name: assessment_interpretations fk_assessment_interpretations_administration; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_interpretations
    ADD CONSTRAINT fk_assessment_interpretations_administration FOREIGN KEY (administration_id) REFERENCES public.assessment_responses(id) ON DELETE CASCADE;


--
-- Name: assessment_interpretations fk_assessment_interpretations_result; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_interpretations
    ADD CONSTRAINT fk_assessment_interpretations_result FOREIGN KEY (result_id) REFERENCES public.assessment_results(id) ON DELETE CASCADE;


--
-- Name: assessment_results fk_assessment_results_administration; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_results
    ADD CONSTRAINT fk_assessment_results_administration FOREIGN KEY (administration_id) REFERENCES public.assessment_responses(id) ON DELETE CASCADE;


--
-- Name: assessment_score_items fk_assessment_score_items_administration; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_score_items
    ADD CONSTRAINT fk_assessment_score_items_administration FOREIGN KEY (administration_id) REFERENCES public.assessment_responses(id) ON DELETE CASCADE;


--
-- Name: assessment_score_items fk_assessment_score_items_result; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_score_items
    ADD CONSTRAINT fk_assessment_score_items_result FOREIGN KEY (result_id) REFERENCES public.assessment_results(id) ON DELETE CASCADE;


--
-- Name: assessment_submission_context fk_assessment_submission_context_administration; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_submission_context
    ADD CONSTRAINT fk_assessment_submission_context_administration FOREIGN KEY (administration_id) REFERENCES public.assessment_responses(id) ON DELETE CASCADE;


--
-- Name: scientific_feature_items fk_scientific_feature_item_vector; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_items
    ADD CONSTRAINT fk_scientific_feature_item_vector FOREIGN KEY (feature_vector_id) REFERENCES public.scientific_feature_vectors(id) ON DELETE CASCADE;


--
-- Name: scientific_feature_generation_runs fk_scientific_feature_run_vector; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scientific_feature_generation_runs
    ADD CONSTRAINT fk_scientific_feature_run_vector FOREIGN KEY (feature_vector_id) REFERENCES public.scientific_feature_vectors(id) ON DELETE SET NULL;


--
-- Name: adaptive_learning_plan_family_actions fka1gqi1egkjh0f9o1vuvtjus0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptive_learning_plan_family_actions
    ADD CONSTRAINT fka1gqi1egkjh0f9o1vuvtjus0x FOREIGN KEY (plan_id) REFERENCES public.adaptive_learning_plans(id);


--
-- Name: assessment_answers fkb31hju83dfbr5pnkj324pnper; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_answers
    ADD CONSTRAINT fkb31hju83dfbr5pnkj324pnper FOREIGN KEY (assessment_response_id) REFERENCES public.assessment_responses(id);


--
-- Name: assessment_options fkc134w3tasx0dc8k2iqvg8d52j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_options
    ADD CONSTRAINT fkc134w3tasx0dc8k2iqvg8d52j FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id);


--
-- Name: adaptive_learning_plan_pathway fkdtl2n1yfuiop82a51svtmv585; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adaptive_learning_plan_pathway
    ADD CONSTRAINT fkdtl2n1yfuiop82a51svtmv585 FOREIGN KEY (plan_id) REFERENCES public.adaptive_learning_plans(id);


--
-- Name: kuder_top_vocational_areas fkex92kjoaqcfawmc9m6y4xrx51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kuder_top_vocational_areas
    ADD CONSTRAINT fkex92kjoaqcfawmc9m6y4xrx51 FOREIGN KEY (assessment_id) REFERENCES public.kuder_assessment_results(id);


--
-- Name: kuder_assessment_answers fknbflwgar1h15psgcs35m1e7ke; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kuder_assessment_answers
    ADD CONSTRAINT fknbflwgar1h15psgcs35m1e7ke FOREIGN KEY (assessment_id) REFERENCES public.kuder_assessment_results(id);


--
-- Name: felder_silverman_answers fkomh12h4913humc3d7dbiw0a6g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.felder_silverman_answers
    ADD CONSTRAINT fkomh12h4913humc3d7dbiw0a6g FOREIGN KEY (assessment_id) REFERENCES public.felder_silverman_assessment_results(id);


--
-- Name: assessment_questions fkoxceireibiwstbc4n53028lvx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_questions
    ADD CONSTRAINT fkoxceireibiwstbc4n53028lvx FOREIGN KEY (assessment_definition_id) REFERENCES public.assessment_definitions(id);


--
-- Name: instrument_question_options fkq92e9029j6k68ngnlfi6x7iwe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instrument_question_options
    ADD CONSTRAINT fkq92e9029j6k68ngnlfi6x7iwe FOREIGN KEY (question_id) REFERENCES public.instrument_questions(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bTFbdteLxXfNV6oqYacRQb5NxOY8mvlYVmZUf6niG7sTFxywX6jeuN9mUeHL7AW

